# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'findArecipe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.TitleLabel = QtWidgets.QLabel(Form)
        self.TitleLabel.setGeometry(QtCore.QRect(10, 50, 781, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.returnTohomeButton = QtWidgets.QPushButton(Form)
        self.returnTohomeButton.setGeometry(QtCore.QRect(290, 350, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.returnTohomeButton.setFont(font)
        self.returnTohomeButton.setStyleSheet("background-color: rgb(139, 196, 190);")
        self.returnTohomeButton.setObjectName("returnTohomeButton")

        self.retranslateUi(Form)
        self.returnTohomeButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "Find a Recipe"))
        self.returnTohomeButton.setText(_translate("Form", "Return to Home"))
